# Generated by Django 5.1.1 on 2024-09-13 02:10

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cuisine_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
