# Generated by Django 5.1.1 on 2024-09-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_description_restaurant_rating_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='added_at',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
